#!/usr/bin/env python3
"""Strip an NDG dumpdata fixture down to models a plain Nautobot install can load.

The NDG JSON artifacts contain objects for ~10 optional Nautobot Apps. `loaddata`
aborts on the first model whose app is not installed, so a local dev instance without
those apps cannot load the fixture as shipped. This drops those objects, and
optionally the changelog/job-log noise that only bloats the load.

Usage:
    python3 filter_ndg_fixture.py nautobot.json nautobot-core.json
    python3 filter_ndg_fixture.py nautobot.json out.json --keep-apps nautobot_golden_config
    python3 filter_ndg_fixture.py nautobot.json out.json --keep-history
"""

import argparse
import collections
import json
import sys

# Apps shipped with Nautobot core. Everything else is an optional App.
CORE_APPS = {
    "auth",
    "circuits",
    "cloud",
    "constance",
    "contenttypes",
    "data_validation",
    "dcim",
    "extras",
    "ipam",
    "tenancy",
    "users",
    "virtualization",
    "vpn",
    "wireless",
}

# Regenerated by Nautobot itself; pure bloat in a seed fixture.
HISTORY_MODELS = {
    "extras.objectchange",
    "extras.joblogentry",
    "extras.jobresult",
    "dcim.cablepath",
}


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("infile")
    parser.add_argument("outfile")
    parser.add_argument(
        "--keep-apps",
        nargs="*",
        default=[],
        metavar="APP_LABEL",
        help="Optional app labels to keep (e.g. nautobot_golden_config). Only keep apps you have installed.",
    )
    parser.add_argument(
        "--keep-history",
        action="store_true",
        help="Keep objectchange/joblogentry/jobresult/cablepath records (default: drop them).",
    )
    args = parser.parse_args()

    keep_apps = CORE_APPS | set(args.keep_apps)

    with open(args.infile, encoding="utf-8") as handle:
        objects = json.load(handle)

    kept, dropped_app, dropped_history = [], collections.Counter(), collections.Counter()
    for obj in objects:
        model = obj["model"]
        app_label = model.split(".")[0]
        if app_label not in keep_apps:
            dropped_app[app_label] += 1
            continue
        if not args.keep_history and model in HISTORY_MODELS:
            dropped_history[model] += 1
            continue
        kept.append(obj)

    with open(args.outfile, "w", encoding="utf-8") as handle:
        json.dump(kept, handle)

    print(f"in:   {len(objects)} objects")
    print(f"out:  {len(kept)} objects -> {args.outfile}")
    if dropped_app:
        print("\ndropped app objects (apps not kept):")
        for app_label, count in dropped_app.most_common():
            print(f"  {app_label:38s} {count}")
    if dropped_history:
        print("\ndropped history/derived objects:")
        for model, count in dropped_history.most_common():
            print(f"  {model:38s} {count}")

    remaining = sorted({o["model"].split(".")[0] for o in kept})
    print("\napps in output:", " ".join(remaining))
    return 0


if __name__ == "__main__":
    sys.exit(main())
